/*
 * To change this license header, choose License Headers in Project Properties.
 * and open the template in the editor.
 */
package PROJECT;
/**
 *
 * @author Admin
 */
public class P5 extends javax.swing.JFrame {

    /**
     * Creates new form P5
     */
    public P5() {
        initComponents();
        setLocationRelativeTo(null);
        A.setVisible(false);a.setVisible(false);AAA.setVisible(false);
        B.setVisible(false);b.setVisible(false);BBB.setVisible(false);
        C.setVisible(false);c.setVisible(false);CCC.setVisible(false);
        D.setVisible(false);d.setVisible(false);DDD.setVisible(false);
        F.setVisible(false);e.setVisible(false);FFF.setVisible(false);
        G.setVisible(false);f.setVisible(false);EEE.setVisible(false);
        H.setVisible(false);g.setVisible(false);
        I.setVisible(false);h.setVisible(false);
        J.setVisible(false);i.setVisible(false);
        E.setVisible(false);j.setVisible(false);
        K.setVisible(false);k.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        A = new javax.swing.JCheckBox();
        B = new javax.swing.JCheckBox();
        C = new javax.swing.JCheckBox();
        D = new javax.swing.JCheckBox();
        E = new javax.swing.JCheckBox();
        F = new javax.swing.JCheckBox();
        G = new javax.swing.JCheckBox();
        H = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        J = new javax.swing.JCheckBox();
        K = new javax.swing.JCheckBox();
        jRadioButton4 = new javax.swing.JRadioButton();
        a = new javax.swing.JCheckBox();
        d = new javax.swing.JCheckBox();
        b = new javax.swing.JCheckBox();
        e = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        f = new javax.swing.JCheckBox();
        g = new javax.swing.JCheckBox();
        h = new javax.swing.JCheckBox();
        i = new javax.swing.JCheckBox();
        j = new javax.swing.JCheckBox();
        k = new javax.swing.JCheckBox();
        jRadioButton2 = new javax.swing.JRadioButton();
        AAA = new javax.swing.JCheckBox();
        BBB = new javax.swing.JCheckBox();
        CCC = new javax.swing.JCheckBox();
        DDD = new javax.swing.JCheckBox();
        EEE = new javax.swing.JCheckBox();
        FFF = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Three Arrows", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("BACHELOR's CUISINE");

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 0, 255));
        jRadioButton1.setText("STARTERS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        A.setBackground(new java.awt.Color(0, 0, 0));
        A.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        A.setForeground(new java.awt.Color(0, 153, 153));
        A.setText("DUMPLINGS");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        B.setBackground(new java.awt.Color(0, 0, 0));
        B.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        B.setForeground(new java.awt.Color(0, 153, 153));
        B.setText("MEAT BALLS");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setBackground(new java.awt.Color(0, 0, 0));
        C.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        C.setForeground(new java.awt.Color(0, 153, 153));
        C.setText("BORITTOS");

        D.setBackground(new java.awt.Color(0, 0, 0));
        D.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        D.setForeground(new java.awt.Color(0, 153, 153));
        D.setText("BAKED WEDGE");

        E.setBackground(new java.awt.Color(0, 0, 0));
        E.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        E.setForeground(new java.awt.Color(0, 153, 153));
        E.setText("CRISPY FINGERS");

        F.setBackground(new java.awt.Color(0, 0, 0));
        F.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        F.setForeground(new java.awt.Color(0, 153, 153));
        F.setText("MEXICAN PEANUTS");

        G.setBackground(new java.awt.Color(0, 0, 0));
        G.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        G.setForeground(new java.awt.Color(0, 153, 153));
        G.setText("GRILLED COTTAGE");

        H.setBackground(new java.awt.Color(0, 0, 0));
        H.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        H.setForeground(new java.awt.Color(0, 153, 153));
        H.setText("HUKKA NOODLES");

        I.setBackground(new java.awt.Color(0, 0, 0));
        I.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        I.setForeground(new java.awt.Color(0, 153, 153));
        I.setText("SCHEZWAN SANDWICH");

        J.setBackground(new java.awt.Color(0, 0, 0));
        J.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        J.setForeground(new java.awt.Color(0, 153, 153));
        J.setText("CIGAR ROLLS");

        K.setBackground(new java.awt.Color(0, 0, 0));
        K.setFont(new java.awt.Font("StudioBold", 1, 18)); // NOI18N
        K.setForeground(new java.awt.Color(0, 153, 153));
        K.setText("GARLIC MUSHROOM SANDWICH");

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(204, 0, 255));
        jRadioButton4.setText("MAIN COURSE");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        a.setForeground(new java.awt.Color(0, 153, 153));
        a.setText("KADHAI PANEER");

        d.setBackground(new java.awt.Color(0, 0, 0));
        d.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        d.setForeground(new java.awt.Color(0, 153, 153));
        d.setText("KADHAI CHICKEN");

        b.setBackground(new java.awt.Color(0, 0, 0));
        b.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        b.setForeground(new java.awt.Color(0, 153, 153));
        b.setText("PANEER TIKKA MASALA");

        e.setBackground(new java.awt.Color(0, 0, 0));
        e.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        e.setForeground(new java.awt.Color(0, 153, 153));
        e.setText("EGG CURRY");

        c.setBackground(new java.awt.Color(0, 0, 0));
        c.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        c.setForeground(new java.awt.Color(0, 153, 153));
        c.setText("DAL TADKA");

        f.setBackground(new java.awt.Color(0, 0, 0));
        f.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        f.setForeground(new java.awt.Color(0, 153, 153));
        f.setText("CHICKEN RAZALA");

        g.setBackground(new java.awt.Color(0, 0, 0));
        g.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        g.setForeground(new java.awt.Color(0, 153, 153));
        g.setText("BUTTER CHICKEN");

        h.setBackground(new java.awt.Color(0, 0, 0));
        h.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        h.setForeground(new java.awt.Color(0, 153, 153));
        h.setText("DAL MAKHNI");

        i.setBackground(new java.awt.Color(0, 0, 0));
        i.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        i.setForeground(new java.awt.Color(0, 153, 153));
        i.setText("KEEMA ROTI");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        j.setBackground(new java.awt.Color(0, 0, 0));
        j.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        j.setForeground(new java.awt.Color(0, 153, 153));
        j.setText("DUM BRIYANI");

        k.setBackground(new java.awt.Color(0, 0, 0));
        k.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        k.setForeground(new java.awt.Color(0, 153, 153));
        k.setText("STEAMED PULAO");

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton2.setText("DESSERTS");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        AAA.setBackground(new java.awt.Color(0, 0, 0));
        AAA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AAA.setForeground(new java.awt.Color(0, 153, 153));
        AAA.setText("MOCHA LAVA CAKE");

        BBB.setBackground(new java.awt.Color(0, 0, 0));
        BBB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BBB.setForeground(new java.awt.Color(0, 153, 153));
        BBB.setText("FLOURLESS CHOCOLATE CAKE");
        BBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBBActionPerformed(evt);
            }
        });

        CCC.setBackground(new java.awt.Color(0, 0, 0));
        CCC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CCC.setForeground(new java.awt.Color(0, 153, 153));
        CCC.setText("BANOFFEE PIE");

        DDD.setBackground(new java.awt.Color(0, 0, 0));
        DDD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DDD.setForeground(new java.awt.Color(0, 153, 153));
        DDD.setText("RASMALAI CHEEZE");

        EEE.setBackground(new java.awt.Color(0, 0, 0));
        EEE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EEE.setForeground(new java.awt.Color(0, 153, 153));
        EEE.setText("HOT BROWN SHAKE");

        FFF.setBackground(new java.awt.Color(0, 0, 0));
        FFF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FFF.setForeground(new java.awt.Color(0, 153, 153));
        FFF.setText("LINDT HOT SHAKE");
        FFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FFFActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CALCULATE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(I)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b)
                            .addComponent(e)
                            .addComponent(h)
                            .addComponent(k))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(F)
                                            .addComponent(A)
                                            .addComponent(D)))
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(E)
                                    .addComponent(G)
                                    .addComponent(B)
                                    .addComponent(K)))
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel1)))
                        .addGap(19, 19, 19)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a)
                            .addComponent(d)
                            .addComponent(g)
                            .addComponent(j))
                        .addGap(340, 340, 340)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(i)
                                .addComponent(f)
                                .addComponent(c))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(C)
                                .addComponent(J)
                                .addComponent(H)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AAA)
                    .addComponent(BBB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DDD)
                        .addGap(18, 18, 18)
                        .addComponent(FFF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CCC)
                        .addGap(59, 59, 59)
                        .addComponent(EEE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(J))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(G)
                        .addComponent(C))
                    .addComponent(F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(H)
                    .addComponent(E)
                    .addComponent(D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I)
                    .addComponent(K))
                .addGap(28, 28, 28)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d)
                    .addComponent(e)
                    .addComponent(f))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g)
                    .addComponent(h)
                    .addComponent(i))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j)
                    .addComponent(k))
                .addGap(21, 21, 21)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CCC)
                        .addComponent(EEE))
                    .addComponent(AAA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBB)
                    .addComponent(DDD)
                    .addComponent(FFF))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        A.setVisible(true);
        B.setVisible(true);
        C.setVisible(true);
        D.setVisible(true);
        E.setVisible(true);
        F.setVisible(true);
        G.setVisible(true);
        H.setVisible(true);
        I.setVisible(true);
        J.setVisible(true);
        K.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        a.setVisible(true);
        b.setVisible(true);
        c.setVisible(true);
        d.setVisible(true);
        e.setVisible(true);
        f.setVisible(true);
        g.setVisible(true);
        h.setVisible(true);
        i.setVisible(true);
        j.setVisible(true);
        k.setVisible(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void BBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBBActionPerformed

    private void FFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FFFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FFFActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        AAA.setVisible(true);
        BBB.setVisible(true);
        CCC.setVisible(true);
        DDD.setVisible(true);
        EEE.setVisible(true);
        FFF.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Q2 UU = new Q2();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          P4 UU = new P4();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A;
    private javax.swing.JCheckBox AAA;
    private javax.swing.JCheckBox B;
    private javax.swing.JCheckBox BBB;
    private javax.swing.JCheckBox C;
    private javax.swing.JCheckBox CCC;
    private javax.swing.JCheckBox D;
    private javax.swing.JCheckBox DDD;
    private javax.swing.JCheckBox E;
    private javax.swing.JCheckBox EEE;
    private javax.swing.JCheckBox F;
    private javax.swing.JCheckBox FFF;
    private javax.swing.JCheckBox G;
    private javax.swing.JCheckBox H;
    private javax.swing.JCheckBox I;
    private javax.swing.JCheckBox J;
    private javax.swing.JCheckBox K;
    private javax.swing.JCheckBox a;
    private javax.swing.JCheckBox b;
    private javax.swing.JCheckBox c;
    private javax.swing.JCheckBox d;
    private javax.swing.JCheckBox e;
    private javax.swing.JCheckBox f;
    private javax.swing.JCheckBox g;
    private javax.swing.JCheckBox h;
    private javax.swing.JCheckBox i;
    private javax.swing.JCheckBox j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JCheckBox k;
    // End of variables declaration//GEN-END:variables
}
