/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROJECT;

/**
 *
 * @author Admin
 */
public class P6 extends javax.swing.JFrame {

    /**
     * Creates new form P6
     */
    public P6() {
        initComponents();
        setLocationRelativeTo(null);
        A.setVisible(false);AA.setVisible(false);AAA.setVisible(false);
        B.setVisible(false);BB.setVisible(false);BBB.setVisible(false);
        C.setVisible(false);CC.setVisible(false);CCC.setVisible(false);
        D.setVisible(false);DD.setVisible(false);DDD.setVisible(false);
        F.setVisible(false);EE.setVisible(false);FFF.setVisible(false);
        FF.setVisible(false);EEE.setVisible(false);
        G.setVisible(false);GG.setVisible(false);
        H.setVisible(false);HH.setVisible(false);
        I.setVisible(false);II.setVisible(false);
        E.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        A = new javax.swing.JCheckBox();
        D = new javax.swing.JCheckBox();
        G = new javax.swing.JCheckBox();
        B = new javax.swing.JCheckBox();
        E = new javax.swing.JCheckBox();
        H = new javax.swing.JCheckBox();
        C = new javax.swing.JCheckBox();
        F = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        jRadioButton2 = new javax.swing.JRadioButton();
        AA = new javax.swing.JCheckBox();
        DD = new javax.swing.JCheckBox();
        GG = new javax.swing.JCheckBox();
        BB = new javax.swing.JCheckBox();
        HH = new javax.swing.JCheckBox();
        EE = new javax.swing.JCheckBox();
        CC = new javax.swing.JCheckBox();
        FF = new javax.swing.JCheckBox();
        II = new javax.swing.JCheckBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        AAA = new javax.swing.JCheckBox();
        DDD = new javax.swing.JCheckBox();
        BBB = new javax.swing.JCheckBox();
        EEE = new javax.swing.JCheckBox();
        CCC = new javax.swing.JCheckBox();
        FFF = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("ActionIs", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("FAMILY GATHERING");

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton1.setText("STARTERS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        A.setBackground(new java.awt.Color(0, 0, 0));
        A.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        A.setForeground(new java.awt.Color(0, 204, 153));
        A.setText("MALAI SOYA CHAAP");

        D.setBackground(new java.awt.Color(0, 0, 0));
        D.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        D.setForeground(new java.awt.Color(0, 204, 153));
        D.setText("ROASTED LEG PIECE");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        G.setBackground(new java.awt.Color(0, 0, 0));
        G.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        G.setForeground(new java.awt.Color(0, 204, 153));
        G.setText("HONEY CHILLI POTATO");

        B.setBackground(new java.awt.Color(0, 0, 0));
        B.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        B.setForeground(new java.awt.Color(0, 204, 153));
        B.setText("CIGAR SHOTS");

        E.setBackground(new java.awt.Color(0, 0, 0));
        E.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        E.setForeground(new java.awt.Color(0, 204, 153));
        E.setText("ITALIAN PIZZA");

        H.setBackground(new java.awt.Color(0, 0, 0));
        H.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        H.setForeground(new java.awt.Color(0, 204, 153));
        H.setText("OVERLOADED SANDWHICH");

        C.setBackground(new java.awt.Color(0, 0, 0));
        C.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        C.setForeground(new java.awt.Color(0, 204, 153));
        C.setText("CRUNCHY STRIPS");

        F.setBackground(new java.awt.Color(0, 0, 0));
        F.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        F.setForeground(new java.awt.Color(0, 204, 153));
        F.setText("THIN CRUST ROLLS");

        I.setBackground(new java.awt.Color(0, 0, 0));
        I.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        I.setForeground(new java.awt.Color(0, 204, 153));
        I.setText("CREAMS NACHOS");

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton2.setText("MAIN COURSE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        AA.setBackground(new java.awt.Color(0, 0, 0));
        AA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AA.setForeground(new java.awt.Color(0, 153, 153));
        AA.setText(" PANEER BUTTER MASALA");

        DD.setBackground(new java.awt.Color(0, 0, 0));
        DD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DD.setForeground(new java.awt.Color(0, 153, 153));
        DD.setText("PANEER CHAMAN BAHAR");

        GG.setBackground(new java.awt.Color(0, 0, 0));
        GG.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        GG.setForeground(new java.awt.Color(0, 153, 153));
        GG.setText("CHICKEN MASALA");

        BB.setBackground(new java.awt.Color(0, 0, 0));
        BB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BB.setForeground(new java.awt.Color(0, 153, 153));
        BB.setText("FISH CURRY");

        HH.setBackground(new java.awt.Color(0, 0, 0));
        HH.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        HH.setForeground(new java.awt.Color(0, 153, 153));
        HH.setText("TOMATO FISH");

        EE.setBackground(new java.awt.Color(0, 0, 0));
        EE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EE.setForeground(new java.awt.Color(0, 153, 153));
        EE.setText("MUTTON ROGAN");

        CC.setBackground(new java.awt.Color(0, 0, 0));
        CC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CC.setForeground(new java.awt.Color(0, 153, 153));
        CC.setText("NOODLES FRIED");

        FF.setBackground(new java.awt.Color(0, 0, 0));
        FF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FF.setForeground(new java.awt.Color(0, 153, 153));
        FF.setText("MANCHURIAN");

        II.setBackground(new java.awt.Color(0, 0, 0));
        II.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        II.setForeground(new java.awt.Color(0, 153, 153));
        II.setText("GRILLED LIMON FISH");

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton3.setText("DESSERTS");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        AAA.setBackground(new java.awt.Color(0, 0, 0));
        AAA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AAA.setForeground(new java.awt.Color(0, 204, 153));
        AAA.setText("SHAHI TUKDA");

        DDD.setBackground(new java.awt.Color(0, 0, 0));
        DDD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DDD.setForeground(new java.awt.Color(0, 204, 153));
        DDD.setText("TOOTY FRUITY");

        BBB.setBackground(new java.awt.Color(0, 0, 0));
        BBB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BBB.setForeground(new java.awt.Color(0, 204, 153));
        BBB.setText("GULAB JAMUN");

        EEE.setBackground(new java.awt.Color(0, 0, 0));
        EEE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EEE.setForeground(new java.awt.Color(0, 204, 153));
        EEE.setText("PHIRNI");

        CCC.setBackground(new java.awt.Color(0, 0, 0));
        CCC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CCC.setForeground(new java.awt.Color(0, 204, 153));
        CCC.setText("FRUIT ICE CREAM");

        FFF.setBackground(new java.awt.Color(0, 0, 0));
        FFF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FFF.setForeground(new java.awt.Color(0, 204, 153));
        FFF.setText("CORNATO");
        FFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FFFActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CALCULATE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D)
                                    .addComponent(G))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(E)
                                            .addComponent(H))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(F)
                                            .addComponent(I)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BB)
                                            .addComponent(EE)
                                            .addComponent(HH)
                                            .addComponent(BBB)
                                            .addComponent(EEE))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(II)
                                            .addComponent(FF)
                                            .addComponent(CC)
                                            .addComponent(CCC)
                                            .addComponent(FFF)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(A)
                                .addGap(70, 70, 70)
                                .addComponent(B)
                                .addGap(157, 157, 157)
                                .addComponent(C))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AA)
                            .addComponent(DD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GG, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DDD)
                            .addComponent(AAA)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(635, 635, 635)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton2)
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A)
                            .addComponent(B)
                            .addComponent(C))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D)
                            .addComponent(E)
                            .addComponent(F))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(G)
                            .addComponent(H)
                            .addComponent(I))
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AA)
                            .addComponent(BB)
                            .addComponent(CC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DD)
                            .addComponent(EE)
                            .addComponent(FF))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GG)
                            .addComponent(HH)
                            .addComponent(II)))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AAA)
                    .addComponent(BBB)
                    .addComponent(CCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DDD)
                    .addComponent(EEE)
                    .addComponent(FFF))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void FFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FFFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FFFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
        Q2 UU = new Q2();
           UU.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         P4 UU = new P4();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        A.setVisible(true);
        B.setVisible(true);
        C.setVisible(true);
        D.setVisible(true);
        E.setVisible(true);
        F.setVisible(true);
        G.setVisible(true);
        H.setVisible(true);
        I.setVisible(true);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        AA.setVisible(true);
        BB.setVisible(true);
        CC.setVisible(true);
        DD.setVisible(true);
        EE.setVisible(true);
        FF.setVisible(true);
        HH.setVisible(true);
        II.setVisible(true);
        GG.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        AAA.setVisible(true);
        BBB.setVisible(true);
        CCC.setVisible(true);
        DDD.setVisible(true);
        EEE.setVisible(true);
        FFF.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A;
    private javax.swing.JCheckBox AA;
    private javax.swing.JCheckBox AAA;
    private javax.swing.JCheckBox B;
    private javax.swing.JCheckBox BB;
    private javax.swing.JCheckBox BBB;
    private javax.swing.JCheckBox C;
    private javax.swing.JCheckBox CC;
    private javax.swing.JCheckBox CCC;
    private javax.swing.JCheckBox D;
    private javax.swing.JCheckBox DD;
    private javax.swing.JCheckBox DDD;
    private javax.swing.JCheckBox E;
    private javax.swing.JCheckBox EE;
    private javax.swing.JCheckBox EEE;
    private javax.swing.JCheckBox F;
    private javax.swing.JCheckBox FF;
    private javax.swing.JCheckBox FFF;
    private javax.swing.JCheckBox G;
    private javax.swing.JCheckBox GG;
    private javax.swing.JCheckBox H;
    private javax.swing.JCheckBox HH;
    private javax.swing.JCheckBox I;
    private javax.swing.JCheckBox II;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
