/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROJECT;

/**
 *
 * @author Admin
 */
public class P7 extends javax.swing.JFrame {

    /**
     * Creates new form P7
     */
    public P7() {
        initComponents();
        setLocationRelativeTo(null);
        A.setVisible(false);AA.setVisible(false);AAA.setVisible(false);
        B.setVisible(false);BB.setVisible(false);BBB.setVisible(false);
        C.setVisible(false);CC.setVisible(false);CCC.setVisible(false);
        D.setVisible(false);DD.setVisible(false);DDD.setVisible(false);
        F.setVisible(false);EE.setVisible(false);
        G.setVisible(false);FF.setVisible(false);
        H.setVisible(false);GG.setVisible(false);
        I.setVisible(false);HH.setVisible(false);
        J.setVisible(false);II.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        A = new javax.swing.JCheckBox();
        D = new javax.swing.JCheckBox();
        H = new javax.swing.JCheckBox();
        B = new javax.swing.JCheckBox();
        F = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        C = new javax.swing.JCheckBox();
        G = new javax.swing.JCheckBox();
        J = new javax.swing.JCheckBox();
        jRadioButton2 = new javax.swing.JRadioButton();
        AA = new javax.swing.JCheckBox();
        DD = new javax.swing.JCheckBox();
        GG = new javax.swing.JCheckBox();
        BB = new javax.swing.JCheckBox();
        EE = new javax.swing.JCheckBox();
        HH = new javax.swing.JCheckBox();
        CC = new javax.swing.JCheckBox();
        FF = new javax.swing.JCheckBox();
        II = new javax.swing.JCheckBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        AAA = new javax.swing.JCheckBox();
        BBB = new javax.swing.JCheckBox();
        CCC = new javax.swing.JCheckBox();
        DDD = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Thug", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("BIRTHDAY CELEBRATION");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 153));
        jRadioButton1.setFont(new java.awt.Font("StudioBold", 3, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton1.setText("STARTERS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        A.setBackground(new java.awt.Color(255, 255, 153));
        A.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        A.setText("HAKKA NOODLES");

        D.setBackground(new java.awt.Color(255, 255, 153));
        D.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        D.setText("FRIED RICE");

        H.setBackground(new java.awt.Color(255, 255, 153));
        H.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        H.setText("SPRING ROLLS");

        B.setBackground(new java.awt.Color(255, 255, 153));
        B.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        B.setText("RED/WHITE SAUCE PASTA");

        F.setBackground(new java.awt.Color(255, 255, 153));
        F.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        F.setText("CHEESE BALLS");

        I.setBackground(new java.awt.Color(255, 255, 153));
        I.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        I.setText("PIZZA");

        C.setBackground(new java.awt.Color(255, 255, 153));
        C.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        C.setText("VEG SEEKH KEBAB");

        G.setBackground(new java.awt.Color(255, 255, 153));
        G.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        G.setText("BURGER");

        J.setBackground(new java.awt.Color(255, 255, 153));
        J.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        J.setText("DUMPLINGS");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 153));
        jRadioButton2.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton2.setText("MAIN COURSE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        AA.setBackground(new java.awt.Color(255, 255, 153));
        AA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AA.setText("SHAHI PANEER");

        DD.setBackground(new java.awt.Color(255, 255, 153));
        DD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DD.setText("JEERA RICE");

        GG.setBackground(new java.awt.Color(255, 255, 153));
        GG.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        GG.setText("VEG PULAO");

        BB.setBackground(new java.awt.Color(255, 255, 153));
        BB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BB.setText("KADAI PANEER");

        EE.setBackground(new java.awt.Color(255, 255, 153));
        EE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EE.setText("DAL TADKA");

        HH.setBackground(new java.awt.Color(255, 255, 153));
        HH.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        HH.setText("DUM ALOO");

        CC.setBackground(new java.awt.Color(255, 255, 153));
        CC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CC.setText("SIZZLER BAKED");

        FF.setBackground(new java.awt.Color(255, 255, 153));
        FF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FF.setText("MIX VEG");

        II.setBackground(new java.awt.Color(255, 255, 153));
        II.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        II.setText("MUSHROOM QUIZ");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 153));
        jRadioButton3.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton3.setText("DESSERTS");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        AAA.setBackground(new java.awt.Color(255, 255, 153));
        AAA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AAA.setText("ICE CREAM");

        BBB.setBackground(new java.awt.Color(255, 255, 153));
        BBB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BBB.setText("MOONGDAAL HALWA");

        CCC.setBackground(new java.awt.Color(255, 255, 153));
        CCC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CCC.setText("CAKE TRUFFEL");

        DDD.setBackground(new java.awt.Color(255, 255, 153));
        DDD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DDD.setText("CHOCOLATE FUGDE");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CALCULATE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DD)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(AA)
                            .addContainerGap(641, Short.MAX_VALUE))
                        .addComponent(GG)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(A)
                                                .addComponent(D)
                                                .addComponent(H))
                                            .addGap(28, 28, 28))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(B)
                                                .addComponent(I))
                                            .addGap(33, 33, 33)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(J)
                                                .addComponent(G)
                                                .addComponent(C)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(F)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EE)
                                                    .addComponent(BB)
                                                    .addComponent(HH)))
                                            .addGap(72, 72, 72)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CC)
                                                .addComponent(FF)
                                                .addComponent(II)))))
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jButton2)
                            .addGap(95, 95, 95)
                            .addComponent(jLabel1)
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(22, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AAA)
                .addGap(18, 18, 18)
                .addComponent(BBB)
                .addGap(10, 10, 10)
                .addComponent(CCC)
                .addGap(18, 18, 18)
                .addComponent(DDD)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(F)
                    .addComponent(G))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H)
                    .addComponent(I)
                    .addComponent(J))
                .addGap(32, 32, 32)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AA)
                    .addComponent(BB)
                    .addComponent(CC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(II)
                            .addComponent(GG)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EE)
                            .addComponent(FF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HH)))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AAA)
                    .addComponent(BBB)
                    .addComponent(CCC)
                    .addComponent(DDD))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Q2 UU = new Q2();
           UU.setVisible(true);        
           super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        P4 UU = new P4();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        A.setVisible(true);
        B.setVisible(true);
        C.setVisible(true);
        D.setVisible(true);
        G.setVisible(true);
        F.setVisible(true);
        H.setVisible(true);
        I.setVisible(true);
        J.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        AA.setVisible(true);
        BB.setVisible(true);
        CC.setVisible(true);
        DD.setVisible(true);
        EE.setVisible(true);
        FF.setVisible(true);
        HH.setVisible(true);
        II.setVisible(true);
        GG.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        AAA.setVisible(true);
        BBB.setVisible(true);
        CCC.setVisible(true);
        DDD.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A;
    private javax.swing.JCheckBox AA;
    private javax.swing.JCheckBox AAA;
    private javax.swing.JCheckBox B;
    private javax.swing.JCheckBox BB;
    private javax.swing.JCheckBox BBB;
    private javax.swing.JCheckBox C;
    private javax.swing.JCheckBox CC;
    private javax.swing.JCheckBox CCC;
    private javax.swing.JCheckBox D;
    private javax.swing.JCheckBox DD;
    private javax.swing.JCheckBox DDD;
    private javax.swing.JCheckBox EE;
    private javax.swing.JCheckBox F;
    private javax.swing.JCheckBox FF;
    private javax.swing.JCheckBox G;
    private javax.swing.JCheckBox GG;
    private javax.swing.JCheckBox H;
    private javax.swing.JCheckBox HH;
    private javax.swing.JCheckBox I;
    private javax.swing.JCheckBox II;
    private javax.swing.JCheckBox J;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
