/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROJECT;

/**
 *
 * @author SSDEC
 */
public class P8 extends javax.swing.JFrame {

    /**
     * Creates new form P8
     */
    public P8() {
        initComponents();
        setLocationRelativeTo(null);
        A.setVisible(false);AA.setVisible(false);AAA.setVisible(false);
        B.setVisible(false);BB.setVisible(false);BBB.setVisible(false);
        C.setVisible(false);CC.setVisible(false);CCC.setVisible(false);
        D.setVisible(false);DD.setVisible(false);DDD.setVisible(false);
        F.setVisible(false);EE.setVisible(false);FFF.setVisible(false);
        FF.setVisible(false);EEE.setVisible(false);
        G.setVisible(false);GG.setVisible(false);
        I.setVisible(false);HH.setVisible(false);
        II.setVisible(false);
        E.setVisible(false);
        H.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        A = new javax.swing.JCheckBox();
        D = new javax.swing.JCheckBox();
        G = new javax.swing.JCheckBox();
        B = new javax.swing.JCheckBox();
        E = new javax.swing.JCheckBox();
        H = new javax.swing.JCheckBox();
        C = new javax.swing.JCheckBox();
        F = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        jRadioButton2 = new javax.swing.JRadioButton();
        AA = new javax.swing.JCheckBox();
        DD = new javax.swing.JCheckBox();
        GG = new javax.swing.JCheckBox();
        BB = new javax.swing.JCheckBox();
        EE = new javax.swing.JCheckBox();
        HH = new javax.swing.JCheckBox();
        CC = new javax.swing.JCheckBox();
        FF = new javax.swing.JCheckBox();
        II = new javax.swing.JCheckBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        AAA = new javax.swing.JCheckBox();
        DDD = new javax.swing.JCheckBox();
        BBB = new javax.swing.JCheckBox();
        EEE = new javax.swing.JCheckBox();
        CCC = new javax.swing.JCheckBox();
        FFF = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Stars and Stripes", 1, 48)); // NOI18N
        jLabel1.setText("WEDDING ANNIVERSARY ");

        jRadioButton1.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton1.setFont(new java.awt.Font("StudioBold", 3, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton1.setText("STARTERS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        A.setBackground(new java.awt.Color(153, 255, 153));
        A.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        A.setText("VEG SPRING ROLL");

        D.setBackground(new java.awt.Color(153, 255, 153));
        D.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        D.setText("THAI POTATOES");

        G.setBackground(new java.awt.Color(153, 255, 153));
        G.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        G.setText("VEG CIGAR");

        B.setBackground(new java.awt.Color(153, 255, 153));
        B.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        B.setText("BARBEQUE CHIPS");

        E.setBackground(new java.awt.Color(153, 255, 153));
        E.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        E.setText("FRIES SIZZLERS");

        H.setBackground(new java.awt.Color(153, 255, 153));
        H.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        H.setText("STICK LOLLIPOP");

        C.setBackground(new java.awt.Color(153, 255, 153));
        C.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        C.setText("CHEESE BALLS");

        F.setBackground(new java.awt.Color(153, 255, 153));
        F.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        F.setText("SPRING ROLLS");

        I.setBackground(new java.awt.Color(153, 255, 153));
        I.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        I.setText("SEEKH KEBAB");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton2.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton2.setText("MAIN COURSE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        AA.setBackground(new java.awt.Color(153, 255, 153));
        AA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AA.setText("DAL TADKA");

        DD.setBackground(new java.awt.Color(153, 255, 153));
        DD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DD.setText("KADAI PANEER");

        GG.setBackground(new java.awt.Color(153, 255, 153));
        GG.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        GG.setText("SHAAHI PANEER");

        BB.setBackground(new java.awt.Color(153, 255, 153));
        BB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BB.setText("MALAI KOFTA");

        EE.setBackground(new java.awt.Color(153, 255, 153));
        EE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EE.setText("SOYA KORMA ");

        HH.setBackground(new java.awt.Color(153, 255, 153));
        HH.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        HH.setText("VEG PULAO");

        CC.setBackground(new java.awt.Color(153, 255, 153));
        CC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CC.setText("JEERA RICE");

        FF.setBackground(new java.awt.Color(153, 255, 153));
        FF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FF.setText("MIXED VEG");

        II.setBackground(new java.awt.Color(153, 255, 153));
        II.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        II.setText("BAKED VEG");

        jRadioButton3.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton3.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton3.setText("DESSERT");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        AAA.setBackground(new java.awt.Color(153, 255, 153));
        AAA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AAA.setText("WARM FUDGE BROWNIE");

        DDD.setBackground(new java.awt.Color(153, 255, 153));
        DDD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DDD.setText("MOONDAAL HALWA");

        BBB.setBackground(new java.awt.Color(153, 255, 153));
        BBB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BBB.setText("GULAB JAMUN");

        EEE.setBackground(new java.awt.Color(153, 255, 153));
        EEE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EEE.setText("TRUFFEL ICE CREAM");

        CCC.setBackground(new java.awt.Color(153, 255, 153));
        CCC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CCC.setText("RAS MALAI");

        FFF.setBackground(new java.awt.Color(153, 255, 153));
        FFF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FFF.setText("SHAHI TUKDA");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CALCULATE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DD)
                                            .addComponent(AA)
                                            .addComponent(GG)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(A)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(D, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(G, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addGap(16, 16, 16))))
                                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B)
                                            .addComponent(E)
                                            .addComponent(H))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(F)
                                            .addComponent(C)
                                            .addComponent(I)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BB)
                                            .addComponent(EE)
                                            .addComponent(HH))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(II)
                                            .addComponent(FF)
                                            .addComponent(CC)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AAA)
                                    .addComponent(DDD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BBB)
                                    .addComponent(EEE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FFF)
                                    .addComponent(CCC)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(E)
                    .addComponent(F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I)
                    .addComponent(G)
                    .addComponent(H))
                .addGap(34, 34, 34)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AA)
                    .addComponent(BB)
                    .addComponent(CC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DD)
                    .addComponent(EE)
                    .addComponent(FF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GG)
                    .addComponent(HH)
                    .addComponent(II))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AAA)
                    .addComponent(BBB)
                    .addComponent(CCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DDD)
                    .addComponent(EEE)
                    .addComponent(FFF))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        P4 UU = new P4();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Q3 UU = new Q3();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        A.setVisible(true);
        B.setVisible(true);
        C.setVisible(true);
        D.setVisible(true);
        G.setVisible(true);
        F.setVisible(true);
        H.setVisible(true);
        I.setVisible(true);
        E.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        AA.setVisible(true);
        BB.setVisible(true);
        CC.setVisible(true);
        DD.setVisible(true);
        EE.setVisible(true);
        FF.setVisible(true);
        HH.setVisible(true);
        II.setVisible(true);
        GG.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        AAA.setVisible(true);
        BBB.setVisible(true);
        CCC.setVisible(true);
        DDD.setVisible(true);
        FFF.setVisible(true);
        EEE.setVisible(true);
       
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A;
    private javax.swing.JCheckBox AA;
    private javax.swing.JCheckBox AAA;
    private javax.swing.JCheckBox B;
    private javax.swing.JCheckBox BB;
    private javax.swing.JCheckBox BBB;
    private javax.swing.JCheckBox C;
    private javax.swing.JCheckBox CC;
    private javax.swing.JCheckBox CCC;
    private javax.swing.JCheckBox D;
    private javax.swing.JCheckBox DD;
    private javax.swing.JCheckBox DDD;
    private javax.swing.JCheckBox E;
    private javax.swing.JCheckBox EE;
    private javax.swing.JCheckBox EEE;
    private javax.swing.JCheckBox F;
    private javax.swing.JCheckBox FF;
    private javax.swing.JCheckBox FFF;
    private javax.swing.JCheckBox G;
    private javax.swing.JCheckBox GG;
    private javax.swing.JCheckBox H;
    private javax.swing.JCheckBox HH;
    private javax.swing.JCheckBox I;
    private javax.swing.JCheckBox II;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
