/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROJECT;

/**
 *
 * @author Admin
 */
public class Q1 extends javax.swing.JFrame {

    /**
     */
    public Q1() {
        initComponents();
        setLocationRelativeTo(null);
        A.setVisible(false);a.setVisible(false);AA.setVisible(false);
        B.setVisible(false);b.setVisible(false);BB.setVisible(false);
        C.setVisible(false);c.setVisible(false);CC.setVisible(false);
        D.setVisible(false);d.setVisible(false);DD.setVisible(false);
        F.setVisible(false);e.setVisible(false);FF.setVisible(false);
        G.setVisible(false);f.setVisible(false);EE.setVisible(false);
        H.setVisible(false);g.setVisible(false);GG.setVisible(false);
        I.setVisible(false);h.setVisible(false);HH.setVisible(false);
        i.setVisible(false);II.setVisible(false);
        E.setVisible(false);j.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        A = new javax.swing.JCheckBox();
        D = new javax.swing.JCheckBox();
        G = new javax.swing.JCheckBox();
        B = new javax.swing.JCheckBox();
        E = new javax.swing.JCheckBox();
        H = new javax.swing.JCheckBox();
        C = new javax.swing.JCheckBox();
        F = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        jRadioButton2 = new javax.swing.JRadioButton();
        AA = new javax.swing.JCheckBox();
        DD = new javax.swing.JCheckBox();
        GG = new javax.swing.JCheckBox();
        BB = new javax.swing.JCheckBox();
        CC = new javax.swing.JCheckBox();
        EE = new javax.swing.JCheckBox();
        FF = new javax.swing.JCheckBox();
        II = new javax.swing.JCheckBox();
        HH = new javax.swing.JCheckBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        a = new javax.swing.JCheckBox();
        f = new javax.swing.JCheckBox();
        b = new javax.swing.JCheckBox();
        g = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        h = new javax.swing.JCheckBox();
        d = new javax.swing.JCheckBox();
        i = new javax.swing.JCheckBox();
        e = new javax.swing.JCheckBox();
        j = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Shlop", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setText("COCKTAIL PARTY");

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton1.setText("STARTERS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        A.setBackground(new java.awt.Color(0, 0, 0));
        A.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        A.setForeground(new java.awt.Color(0, 204, 153));
        A.setText("CHICKEN WINGS");

        D.setBackground(new java.awt.Color(0, 0, 0));
        D.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        D.setForeground(new java.awt.Color(0, 204, 153));
        D.setText("GOLDEN FRIED CHICKEN");

        G.setBackground(new java.awt.Color(0, 0, 0));
        G.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        G.setForeground(new java.awt.Color(0, 204, 153));
        G.setText("CHICKEN SATAYA");

        B.setBackground(new java.awt.Color(0, 0, 0));
        B.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        B.setForeground(new java.awt.Color(0, 204, 153));
        B.setText("MASALA PAPAD");

        E.setBackground(new java.awt.Color(0, 0, 0));
        E.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        E.setForeground(new java.awt.Color(0, 204, 153));
        E.setText("FISH FRY");

        H.setBackground(new java.awt.Color(0, 0, 0));
        H.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        H.setForeground(new java.awt.Color(0, 204, 153));
        H.setText("LEMON FISH");

        C.setBackground(new java.awt.Color(0, 0, 0));
        C.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        C.setForeground(new java.awt.Color(0, 204, 153));
        C.setText("MUTTON CHAAP");

        F.setBackground(new java.awt.Color(0, 0, 0));
        F.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        F.setForeground(new java.awt.Color(0, 204, 153));
        F.setText("CHICKEN LOLLIPOP");

        I.setBackground(new java.awt.Color(0, 0, 0));
        I.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        I.setForeground(new java.awt.Color(0, 204, 153));
        I.setText("ROASTED CHICKEN");

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton2.setText("MAIN COURSE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        AA.setBackground(new java.awt.Color(0, 0, 0));
        AA.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        AA.setForeground(new java.awt.Color(0, 204, 153));
        AA.setText("CHICKEN DO PYAZA");

        DD.setBackground(new java.awt.Color(0, 0, 0));
        DD.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        DD.setForeground(new java.awt.Color(0, 204, 153));
        DD.setText("CHICKEN PATIYALA");

        GG.setBackground(new java.awt.Color(0, 0, 0));
        GG.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        GG.setForeground(new java.awt.Color(0, 204, 153));
        GG.setText("CHICKEN KAALI MIRCH");

        BB.setBackground(new java.awt.Color(0, 0, 0));
        BB.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        BB.setForeground(new java.awt.Color(0, 204, 153));
        BB.setText("MUTTON HANDI");

        CC.setBackground(new java.awt.Color(0, 0, 0));
        CC.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        CC.setForeground(new java.awt.Color(0, 204, 153));
        CC.setText("MUTTON LAHORI");

        EE.setBackground(new java.awt.Color(0, 0, 0));
        EE.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        EE.setForeground(new java.awt.Color(0, 204, 153));
        EE.setText("FISH MASALA");

        FF.setBackground(new java.awt.Color(0, 0, 0));
        FF.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        FF.setForeground(new java.awt.Color(0, 204, 153));
        FF.setText("SHAHI PANEER");

        II.setBackground(new java.awt.Color(0, 0, 0));
        II.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        II.setForeground(new java.awt.Color(0, 204, 153));
        II.setText("KADHAI PANEER");

        HH.setBackground(new java.awt.Color(0, 0, 0));
        HH.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        HH.setForeground(new java.awt.Color(0, 204, 153));
        HH.setText("BAKED VEG");

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(204, 0, 204));
        jRadioButton3.setText("DRINKS");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        a.setForeground(new java.awt.Color(0, 204, 153));
        a.setText("CHIVAS 12 YRS");

        f.setBackground(new java.awt.Color(0, 0, 0));
        f.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        f.setForeground(new java.awt.Color(0, 204, 153));
        f.setText("BLACK LABEL");

        b.setBackground(new java.awt.Color(0, 0, 0));
        b.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        b.setForeground(new java.awt.Color(0, 204, 153));
        b.setText("JACK DANIAL");

        g.setBackground(new java.awt.Color(0, 0, 0));
        g.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        g.setForeground(new java.awt.Color(0, 204, 153));
        g.setText("BLACK DOG");

        c.setBackground(new java.awt.Color(0, 0, 0));
        c.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        c.setForeground(new java.awt.Color(0, 204, 153));
        c.setText("BLENDER,S");

        h.setBackground(new java.awt.Color(0, 0, 0));
        h.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        h.setForeground(new java.awt.Color(0, 204, 153));
        h.setText("RED WINE/WHITE");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });

        d.setBackground(new java.awt.Color(0, 0, 0));
        d.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        d.setForeground(new java.awt.Color(0, 204, 153));
        d.setText("KINGFISHER");

        i.setBackground(new java.awt.Color(0, 0, 0));
        i.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        i.setForeground(new java.awt.Color(0, 204, 153));
        i.setText("CORONA");

        e.setBackground(new java.awt.Color(0, 0, 0));
        e.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        e.setForeground(new java.awt.Color(0, 204, 153));
        e.setText("BREEZER");

        j.setBackground(new java.awt.Color(0, 0, 0));
        j.setFont(new java.awt.Font("StudioBold", 0, 18)); // NOI18N
        j.setForeground(new java.awt.Color(0, 204, 153));
        j.setText("CARLSBERG");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CALCULATE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A)
                            .addComponent(G)
                            .addComponent(D))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B)
                            .addComponent(E)
                            .addComponent(H)
                            .addComponent(BB)
                            .addComponent(EE)
                            .addComponent(HH))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I)
                            .addComponent(F)
                            .addComponent(C)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(II))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DD)
                                    .addComponent(AA))
                                .addGap(279, 279, 279)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CC)
                                    .addComponent(FF)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a)
                                    .addComponent(f))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b)
                                    .addComponent(g))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c)
                                        .addGap(18, 18, 18)
                                        .addComponent(d)
                                        .addGap(28, 28, 28)
                                        .addComponent(e))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(h)
                                        .addGap(18, 18, 18)
                                        .addComponent(i)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j))))
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton2)))
                .addGap(9, 9, 9)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(E)
                    .addComponent(F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G)
                    .addComponent(H)
                    .addComponent(I))
                .addGap(32, 32, 32)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AA)
                    .addComponent(BB)
                    .addComponent(CC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DD)
                    .addComponent(EE)
                    .addComponent(FF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(II)
                    .addComponent(GG)
                    .addComponent(HH))
                .addGap(30, 30, 30)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d)
                    .addComponent(e))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f)
                    .addComponent(g)
                    .addComponent(h)
                    .addComponent(i)
                    .addComponent(j))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        P4 UU = new P4();
        UU.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Q2 UU = new Q2();
           UU.setVisible(true);
           super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        A.setVisible(true);
        B.setVisible(true);
        C.setVisible(true);
        D.setVisible(true);
        E.setVisible(true);
        G.setVisible(true);
        F.setVisible(true);
        H.setVisible(true);
        I.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        AA.setVisible(true);
        BB.setVisible(true);
        CC.setVisible(true);
        DD.setVisible(true);
        EE.setVisible(true);
        FF.setVisible(true);
        GG.setVisible(true);
        HH.setVisible(true);
        II.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        a.setVisible(true);
        b.setVisible(true);
        c.setVisible(true);
        d.setVisible(true);
        e.setVisible(true);
        f.setVisible(true);
        g.setVisible(true);
        h.setVisible(true);
        g.setVisible(true);
        h.setVisible(true);
        i.setVisible(true);
        j.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Q1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A;
    private javax.swing.JCheckBox AA;
    private javax.swing.JCheckBox B;
    private javax.swing.JCheckBox BB;
    private javax.swing.JCheckBox C;
    private javax.swing.JCheckBox CC;
    private javax.swing.JCheckBox D;
    private javax.swing.JCheckBox DD;
    private javax.swing.JCheckBox E;
    private javax.swing.JCheckBox EE;
    private javax.swing.JCheckBox F;
    private javax.swing.JCheckBox FF;
    private javax.swing.JCheckBox G;
    private javax.swing.JCheckBox GG;
    private javax.swing.JCheckBox H;
    private javax.swing.JCheckBox HH;
    private javax.swing.JCheckBox I;
    private javax.swing.JCheckBox II;
    private javax.swing.JCheckBox a;
    private javax.swing.JCheckBox b;
    private javax.swing.JCheckBox c;
    private javax.swing.JCheckBox d;
    private javax.swing.JCheckBox e;
    private javax.swing.JCheckBox f;
    private javax.swing.JCheckBox g;
    private javax.swing.JCheckBox h;
    private javax.swing.JCheckBox i;
    private javax.swing.JCheckBox j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
